kind: Namespace
apiVersion: v1
metadata:
  name: ipvs-operator
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ipvs-operator
  namespace: ipvs-operator
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: weightedservices.codesink.net
spec:
  group: codesink.net
  names:
    kind: WeightedService
    listKind: WeightedServiceList
    plural: weightedservices
    singular: weightedservice
  scope: Namespaced
  version: v1alpha1
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ipvs-operator
rules:
- apiGroups:
  - codesink.net
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-ipvs-operator
subjects:
- kind: ServiceAccount
  name: ipvs-operator
  namespace: ipvs-operator
roleRef:
  kind: ClusterRole
  name: ipvs-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ipvs-operator
  namespace: ipvs-operator
spec:
  selector:
    matchLabels:
      name: ipvs-operator
  template:
    metadata:
      labels:
        name: ipvs-operator
    spec:
      serviceAccountName: ipvs-operator
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      hostNetwork: true
      containers:
        - name: ipvs-operator
          image: justinbarrick/ipvs-operator:v0.0.1
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
          ports:
          - containerPort: 60000
            name: metrics
          env:
          - name: OPERATOR_NAME
            value: "ipvs-operator"
